application: memodotdo
version: 1
runtime: python
api_version: 1

handlers:

- url: /styles
  static_dir: css
  
- url: /scripts
  static_dir: js

- url: /images
  static_dir: img

- url: /favicon.ico
  static_files: img/favicon.ico
  upload: img/favicon.ico
  
- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt
  
- url: /.*
  script: main.py
